#name: Run tests
name: ML Pipeline CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pandas numpy scikit-learn great_expectations flake8 black

      - name: Lint with flake8
        run: |
          flake8 day5/演習3 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 day5/演習3 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        
      - name: Format check with black
        run: |
          black --check day5/演習3
        
      - name: Run data tests
        run: |
          pytest day5/演習3/tests/test_data.py -v
        
      - name: Run model tests
        run: |
          pytest day5/演習3/tests/test_model.py -v
        